Taking in the original rates tables and trimming to our study's time period + adding a stage names column

In [5]:
import pandas as pd

In [18]:
# Function to format the rates tables

from pandas import NA

def format_rates_table(df):
    df = df.copy()
    # make the age colum positive, by multiplying it by -1
    df['age'] = df['age'] * -1
    # Remove all rows where the 'age' column is > 280 or < 235
    df = df[(df['age'] <= 280) & (df['age'] >= 235)]
    # Add a new column, first column, called 'stage', empty for now
    df.insert(0, 'stage', '')
    # 'stage' should be a string that is based on the 'age' column, but with the following rules:
    df['stage'] = df['age'].apply(lambda x:
        'Kungurian'     if 274.4 < x <= 283.3 else
        'Roadian'       if 266.9 < x <= 274.4 else
        'Wordian'       if 264.28 < x <= 266.9 else
        'Capitanian'    if 259.51 < x <= 264.28 else
        'Wuchiapingian' if 254.14 < x <= 259.51 else
        'Changhsingian' if 251.902 < x <= 254.14 else
        'Induan'        if 249.9 < x <= 251.902 else
        'Olenekian'     if 246.7 < x <= 249.9 else
        'Anisian'       if 241.464 < x <= 246.7 else
        'Ladinian'      if 237 < x <= 241.464 else
        'Carnian'       if 227.3 < x <= 237 else
         ''    )
    # return the age column back to negatives
    df['age'] = df['age'] * -1
    return df

In [19]:
# Want to run this on the rates tables parent folder, 7 subfolders with 2 csvs each in them
# need to load in all csv, run function, save as new csv in same folder with _formatted at the end of the name

import os
def format_entire_folder(parent_folder):
    for subfolder in os.listdir(parent_folder):
        subfolder_path = os.path.join(parent_folder, subfolder)
        if os.path.isdir(subfolder_path):
            for file in os.listdir(subfolder_path):
                if file.endswith('.csv') and not file.endswith('_formatted.csv'):
                    file_path = os.path.join(subfolder_path, file)
                    df = pd.read_csv(file_path)
                    formatted_df = format_rates_table(df)
                    new_file_name = file.replace('.csv', '_formatted.csv')
                    new_file_path = os.path.join(subfolder_path, new_file_name)
                    formatted_df.to_csv(new_file_path, index=False)

In [20]:
# if I need to rerun the above code, I'll need to delete the _formatted csvs first

def delete_formatted_csvs(parent_folder):
    for subfolder in os.listdir(parent_folder):
        subfolder_path = os.path.join(parent_folder, subfolder)
        if os.path.isdir(subfolder_path):
            for file in os.listdir(subfolder_path):
                if file.endswith('_formatted.csv'):
                    file_path = os.path.join(subfolder_path, file)
                    os.remove(file_path)

In [21]:
format_entire_folder("C:\\Users\\SimoesLabAdmin\\Documents\\pt_diversity_rates\\updated_occurrence_analyses\\rates_tables\\formatted_rates_tables")

In [17]:
delete_formatted_csvs("C:\\Users\\SimoesLabAdmin\\Documents\\pt_diversity_rates\\updated_occurrence_analyses\\rates_tables\\formatted_rates_tables")

In [10]:
test = pd.read_csv("C:\\Users\\SimoesLabAdmin\\Documents\\pt_diversity_rates\\updated_occurrence_analyses\\rates_tables\\formatted_rates_tables\\model_1\\rep_terr_model_1_rtt_output_table.csv")
test

,age,L_mean,L_hpd_m95,L_hpd_M95,M_mean,M_hpd_m95,M_hpd_M95,R_mean,R_hpd_m95,R_hpd_M95
0,-200,0.130638,0.086023,0.177356,0.351123,0.269137,0.437642,-0.220485,-0.308983,-0.127800
1,-201,0.130638,0.086023,0.177356,0.351123,0.269137,0.437642,-0.220485,-0.308983,-0.127800
2,-202,0.130638,0.086023,0.177356,0.351123,0.269137,0.437642,-0.220485,-0.308983,-0.127800
3,-203,0.130638,0.086023,0.177356,0.351123,0.269137,0.437642,-0.220485,-0.308983,-0.127800
4,-204,0.130638,0.086023,0.177356,0.351123,0.269137,0.437642,-0.220485,-0.308983,-0.127800
...,...,...,...,...,...,...,...,...,...,...
93,-293,0.391772,0.126809,0.720715,0.143232,0.017856,0.311137,0.248540,-0.042615,0.590219
94,-294,0.391772,0.126809,0.720715,0.143232,0.017856,0.311137,0.248540,-0.042615,0.590219
95,-295,0.391772,0.126809,0.720715,0.143232,0.017856,0.311137,0.248540,-0.042615,0.590219
96,-296,0.391772,0.126809,0.720715,0.143232,0.017856,0.311137,0.248540,-0.042615,0.590219
97,-297,0.391772,0.126809,0.720715,0.143232,0.017856,0.311137,0.248540,-0.042615,0.590219

In [11]:
test_formatted = format_rates_table(test)
test_formatted

Empty DataFrame
Columns: [stage, age, L_mean, L_hpd_m95, L_hpd_M95, M_mean, M_hpd_m95, M_hpd_M95, R_mean, R_hpd_m95, R_hpd_M95]
Index: []